### PR TITLE
With 81xx driver

### PR DESCRIPTION
**Pull request by alfert**
Added the configuration to include the 81xx driver as module for one of the popular USB WiFi dongles. 

This works together with the updated `hello_wifi` example (see https://github.com/nerves-project/nerves-examples/pull/41) without any further changes.

### CODE REVIEW

**Comment by fhunleth** [comment]
The changes look good. Could you add a note in the README.md about the wifi driver? Could you also add the brand name and model for your wifi module as well (even though I haven't gotten to it yet for the others drivers)?

Also, we got your other PRs, but have a small backlog due to recent conferences and work deadlines. Thanks for sending them and we'll get to them soon!

**Comment by GregMefford** [comment]
@fhunleth we don't need the `Config.in` file added, right? Other than that, this change looks good to me. We should definitely get it merged before our next System release.

**Comment by mobileoverlord** [comment]
@GregMefford that's correct, we don't need the Config.in file.

**Comment by fhunleth** [comment]
I rebased the commits on master, removed Config.in, and reworded the firmware installation commit message. The changes are now in master. Thanks!

**Pull request closed without merging**
